"use client";

import { useState, useMemo, useCallback } from "react";
import { useTranslations } from "next-intl";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ExerciseCard, type ExerciseData } from "@/components/exercises/exercise-card";
import { IdentificationExercise } from "@/components/exercises/identification-exercise";
import { CompletionExercise } from "@/components/exercises/completion-exercise";
import { ExerciseFeedback } from "@/components/exercises/exercise-feedback";
import { ExerciseProgress, type FigureProgress } from "@/components/exercises/exercise-progress";
import { checkAnswer } from "@/lib/exercises/check-answer";
// ---------------------------------------------------------------------------
// Inline spinner SVG for loading state
// ---------------------------------------------------------------------------
function Spinner({ className }: { className?: string }) {
  return (
    <svg
      className={cn("animate-spin", className)}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
      />
    </svg>
  );
}

// ---------------------------------------------------------------------------
// Exercise data (mirrors seed data for demo — in production, fetched from DB)
// ---------------------------------------------------------------------------

interface RawExercise {
  id: number;
  figureId: number;
  figureName: string;
  figureSlug: string;
  type: "identification" | "completion";
  prompt: string;
  options: string[] | null;
  correctAnswer: string;
  difficultyLevel: number;
  /** True if this exercise was generated by AI, not from seed data */
  generated?: boolean;
}

const ALL_EXERCISES: RawExercise[] = [
  // Difficulty 1 — Principiante
  { id: 1, figureId: 1, figureName: "Metáfora", figureSlug: "metafora", type: "identification", prompt: '¿Qué figura retórica encontramos en el verso "la vida es sueño, y los sueños, sueños son"?', options: ["Metáfora", "Símil", "Hipérbole", "Personificación"], correctAnswer: "Metáfora", difficultyLevel: 1 },
  { id: 2, figureId: 1, figureName: "Metáfora", figureSlug: "metafora", type: "completion", prompt: 'Completa la metáfora de Pablo Neruda: "Quiero hacer contigo lo que la ________ hace con los cerezos."', options: null, correctAnswer: "primavera", difficultyLevel: 1 },
  { id: 3, figureId: 2, figureName: "Símil", figureSlug: "simil", type: "identification", prompt: '¿Qué figura retórica usa José Martí cuando escribe "Mírame, madre, llorando / como un pájaro sin nido"?', options: ["Metáfora", "Símil", "Antítesis", "Anáfora"], correctAnswer: "Símil", difficultyLevel: 1 },
  { id: 4, figureId: 2, figureName: "Símil", figureSlug: "simil", type: "completion", prompt: 'Completa el símil de Sor Juana: "Como el ave sin ________ que vaga de rama en rama, así vaga mi cuidado."', options: null, correctAnswer: "arrimo", difficultyLevel: 1 },
  { id: 5, figureId: 3, figureName: "Hipérbole", figureSlug: "hiperbole", type: "identification", prompt: '¿Qué figura retórica utiliza Gabriel García Márquez al escribir que la lluvia "no cesó en cuatro años, once meses y dos días"?', options: ["Hipérbole", "Metonimia", "Polisíndeton", "Eufemismo"], correctAnswer: "Hipérbole", difficultyLevel: 1 },
  { id: 6, figureId: 3, figureName: "Hipérbole", figureSlug: "hiperbole", type: "completion", prompt: 'Completa la hipérbole de Mario Benedetti: "Tardé en conocerme toda una ________."', options: null, correctAnswer: "vida", difficultyLevel: 1 },
  { id: 7, figureId: 4, figureName: "Personificación", figureSlug: "personificacion", type: "identification", prompt: '¿Qué figura retórica emplea Juan Rulfo al escribir "el viento gemía en los alambrados"?', options: ["Aliteración", "Personificación", "Onomatopeya", "Hipérbaton"], correctAnswer: "Personificación", difficultyLevel: 1 },
  { id: 8, figureId: 4, figureName: "Personificación", figureSlug: "personificacion", type: "completion", prompt: 'Completa: "El amor es una ________ que siempre está encendida." (Antonio Machado)', options: null, correctAnswer: "hoguera", difficultyLevel: 1 },
  { id: 9, figureId: 6, figureName: "Onomatopeya", figureSlug: "onomatopeya", type: "identification", prompt: '¿Qué figura encontramos en "tic-tac del reloj" y "plic, plac" de la lluvia?', options: ["Aliteración", "Onomatopeya", "Paronomasia", "Hipérbaton"], correctAnswer: "Onomatopeya", difficultyLevel: 1 },
  { id: 10, figureId: 6, figureName: "Onomatopeya", figureSlug: "onomatopeya", type: "completion", prompt: 'Completa: "¡________-________-________...!" (el sonido del saltamontes, Lorca)', options: null, correctAnswer: "cric-cric-cric", difficultyLevel: 1 },
  // Difficulty 2 — Intermedio
  { id: 11, figureId: 5, figureName: "Aliteración", figureSlug: "aliteracion", type: "identification", prompt: '¿Qué figura usa Rubén Darío en "Con el ala aleve del leve abanico"?', options: ["Anáfora", "Aliteración", "Paralelismo", "Asíndeton"], correctAnswer: "Aliteración", difficultyLevel: 2 },
  { id: 12, figureId: 5, figureName: "Aliteración", figureSlug: "aliteracion", type: "completion", prompt: 'La aliteración de Garcilaso repite el sonido de la letra "____" para imitar el zumbido de las abejas.', options: null, correctAnswer: "s", difficultyLevel: 2 },
  { id: 13, figureId: 7, figureName: "Hipérbaton", figureSlug: "hiperbaton", type: "identification", prompt: '¿Qué figura altera el orden lógico de las palabras como hace Góngora?', options: ["Anáfora", "Hipérbaton", "Paralelismo", "Polisíndeton"], correctAnswer: "Hipérbaton", difficultyLevel: 2 },
  { id: 14, figureId: 7, figureName: "Hipérbaton", figureSlug: "hiperbaton", type: "completion", prompt: 'Completa: "A mis ________ voy, de mis ________ vengo." (Lope de Vega)', options: null, correctAnswer: "soledades", difficultyLevel: 2 },
  { id: 15, figureId: 8, figureName: "Anáfora", figureSlug: "anafora", type: "identification", prompt: '¿Qué figura repite palabras al inicio de versos, como el "para" de Neruda?', options: ["Anáfora", "Paralelismo", "Polisíndeton", "Aliteración"], correctAnswer: "Anáfora", difficultyLevel: 2 },
  { id: 16, figureId: 8, figureName: "Anáfora", figureSlug: "anafora", type: "completion", prompt: 'Completa: "No cerrarás los ojos, / no ________, / no te irás..." (Sabines)', options: null, correctAnswer: "morirás", difficultyLevel: 2 },
  { id: 17, figureId: 9, figureName: "Paralelismo", figureSlug: "paralelismo", type: "identification", prompt: '¿Qué figura repite la misma estructura sintáctica en varios versos?', options: ["Anáfora", "Paralelismo", "Antítesis", "Polisíndeton"], correctAnswer: "Paralelismo", difficultyLevel: 2 },
  { id: 18, figureId: 9, figureName: "Paralelismo", figureSlug: "paralelismo", type: "completion", prompt: 'Completa: "Es tan corto el amor, y tan ________ el olvido." (Neruda)', options: null, correctAnswer: "largo", difficultyLevel: 2 },
  { id: 19, figureId: 10, figureName: "Oxímoron", figureSlug: "oximoron", type: "identification", prompt: '¿Qué figura une términos opuestos como "hielo abrasador" y "fuego helado"?', options: ["Antítesis", "Oxímoron", "Paradoja", "Hipérbole"], correctAnswer: "Oxímoron", difficultyLevel: 2 },
  { id: 20, figureId: 10, figureName: "Oxímoron", figureSlug: "oximoron", type: "completion", prompt: 'Completa: "La música ________, la soledad sonora." (San Juan de la Cruz)', options: null, correctAnswer: "callada", difficultyLevel: 2 },
  { id: 21, figureId: 11, figureName: "Antítesis", figureSlug: "antitesis", type: "identification", prompt: '¿Qué figura contrapone ideas opuestas como "corto el amor, largo el olvido"?', options: ["Oxímoron", "Antítesis", "Paralelismo", "Ironía"], correctAnswer: "Antítesis", difficultyLevel: 2 },
  { id: 22, figureId: 11, figureName: "Antítesis", figureSlug: "antitesis", type: "completion", prompt: 'Completa: "Soy un fue, y un será, y un ________ cansado." (Quevedo)', options: null, correctAnswer: "es", difficultyLevel: 2 },
  { id: 23, figureId: 12, figureName: "Eufemismo", figureSlug: "eufemismo", type: "identification", prompt: '¿Qué figura evita nombrar directamente algo tabú o desagradable?', options: ["Metonimia", "Eufemismo", "Símil", "Sinécdoque"], correctAnswer: "Eufemismo", difficultyLevel: 2 },
  { id: 24, figureId: 12, figureName: "Eufemismo", figureSlug: "eufemismo", type: "completion", prompt: 'Completa: "Se nos fue... como se van las tardes, / ________, casi sin sentir." (Machado)', options: null, correctAnswer: "calladamente", difficultyLevel: 2 },
  { id: 25, figureId: 15, figureName: "Metonimia", figureSlug: "metonimia", type: "identification", prompt: '¿Qué figura designa algo con el nombre de otra cosa relacionada, como "leí a Borges"?', options: ["Sinécdoque", "Metonimia", "Metáfora", "Símil"], correctAnswer: "Metonimia", difficultyLevel: 2 },
  { id: 26, figureId: 15, figureName: "Metonimia", figureSlug: "metonimia", type: "completion", prompt: 'Completa: "El ________ se levantó contra la tiranía." (Martí — el material por las armas)', options: null, correctAnswer: "acero", difficultyLevel: 2 },
  { id: 27, figureId: 20, figureName: "Paronomasia", figureSlug: "paronomasia", type: "identification", prompt: '¿Qué figura juega con palabras de sonido similar pero significado diferente?', options: ["Aliteración", "Paronomasia", "Onomatopeya", "Sinestesia"], correctAnswer: "Paronomasia", difficultyLevel: 2 },
  { id: 28, figureId: 20, figureName: "Paronomasia", figureSlug: "paronomasia", type: "completion", prompt: 'Completa: "Que la pluma es la ________ de la alborada." (Quevedo)', options: null, correctAnswer: "espuma", difficultyLevel: 2 },
  // Difficulty 3 — Avanzado
  { id: 29, figureId: 13, figureName: "Ironía", figureSlug: "ironia", type: "identification", prompt: '¿Qué figura da a entender lo contrario de lo que se dice?', options: ["Sarcasmo", "Ironía", "Paradoja", "Humor"], correctAnswer: "Ironía", difficultyLevel: 3 },
  { id: 30, figureId: 13, figureName: "Ironía", figureSlug: "ironia", type: "completion", prompt: 'Completa: "En este país no se lee porque no se ________." (Borges)', options: null, correctAnswer: "escribe", difficultyLevel: 3 },
  { id: 31, figureId: 14, figureName: "Sinestesia", figureSlug: "sinestesia", type: "identification", prompt: '¿Qué figura mezcla sensaciones de diferentes sentidos, como "verdes sonidos"?', options: ["Metonimia", "Sinestesia", "Metáfora", "Paronomasia"], correctAnswer: "Sinestesia", difficultyLevel: 3 },
  { id: 32, figureId: 14, figureName: "Sinestesia", figureSlug: "sinestesia", type: "completion", prompt: 'Completa: "El ________ sonoro de tu mirada." (Darío)', options: null, correctAnswer: "azul", difficultyLevel: 3 },
  { id: 33, figureId: 16, figureName: "Sinécdoque", figureSlug: "sinecdoque", type: "identification", prompt: '¿Qué figura designa el todo por la parte, como "sal" por el agua del mar?', options: ["Metonimia", "Sinécdoque", "Eufemismo", "Metáfora"], correctAnswer: "Sinécdoque", difficultyLevel: 3 },
  { id: 34, figureId: 16, figureName: "Sinécdoque", figureSlug: "sinecdoque", type: "completion", prompt: 'Completa: "Contando los ________ como si cada uno fuera un año de nuestra vida." (Benedetti)', options: null, correctAnswer: "peldaños", difficultyLevel: 3 },
  { id: 35, figureId: 17, figureName: "Polisíndeton", figureSlug: "polisindeton", type: "identification", prompt: '¿Qué figura repite conjunciones innecesariamente ("y... y... y...")?', options: ["Anáfora", "Polisíndeton", "Asíndeton", "Paralelismo"], correctAnswer: "Polisíndeton", difficultyLevel: 3 },
  { id: 36, figureId: 17, figureName: "Polisíndeton", figureSlug: "polisindeton", type: "completion", prompt: 'Completa: "En los hoteles y en los ________ / y en las iglesias y en los almacenes." (Vallejo)', options: null, correctAnswer: "hospitales", difficultyLevel: 3 },
  { id: 37, figureId: 18, figureName: "Asíndeton", figureSlug: "asindeton", type: "identification", prompt: '¿Qué figura omite las conjunciones entre palabras ("Plaza, jabón, toalla, agua...")?', options: ["Polisíndeton", "Asíndeton", "Anáfora", "Enumeración"], correctAnswer: "Asíndeton", difficultyLevel: 3 },
  { id: 38, figureId: 18, figureName: "Asíndeton", figureSlug: "asindeton", type: "completion", prompt: 'Completa: "Vino, mujer, tabaco, noche, / madrugada, sueño, ________." (Valle-Inclán)', options: null, correctAnswer: "olvido", difficultyLevel: 3 },
  { id: 39, figureId: 19, figureName: "Anacoluto", figureSlug: "anacoluto", type: "identification", prompt: '¿Qué figura rompe la estructura sintáctica de una oración ("Yo... bueno... que me voy")?', options: ["Hipérbaton", "Anacoluto", "Elipsis", "Asíndeton"], correctAnswer: "Anacoluto", difficultyLevel: 3 },
  { id: 40, figureId: 19, figureName: "Anacoluto", figureSlug: "anacoluto", type: "completion", prompt: 'Completa: "________, cuando me pongo a caminar, / me parece que el mundo se acaba." (Mistral)', options: null, correctAnswer: "Yo", difficultyLevel: 3 },
];

// ---------------------------------------------------------------------------
// Difficulty labels and colors
// ---------------------------------------------------------------------------

const DIFFICULTY_CONFIG = [
  { level: 1, label: "Principiante", labelEn: "Beginner", color: "bg-emerald-100 text-emerald-700 border-emerald-200" },
  { level: 2, label: "Intermedio", labelEn: "Intermediate", color: "bg-amber-100 text-amber-700 border-amber-200" },
  { level: 3, label: "Avanzado", labelEn: "Advanced", color: "bg-rose-100 text-rose-700 border-rose-200" },
] as const;

// ---------------------------------------------------------------------------
// ExercisePage
// ---------------------------------------------------------------------------

export default function ExercisePage() {
  const t = useTranslations("exercises");

  // State
  const [activeExerciseId, setActiveExerciseId] = useState<number | null>(null);
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState<Record<number, boolean>>({});
  const [results, setResults] = useState<Record<number, boolean>>({});

  // AI generation state: a map of exercise id -> replacement data
  const [generatedExercises, setGeneratedExercises] = useState<
    Record<number, { prompt: string; correctAnswer: string; generated: boolean }>
  >({});
  const [generatingIds, setGeneratingIds] = useState<Set<number>>(new Set());
  const [generateError, setGenerateError] = useState<string | null>(null);

  // Derive the effective exercise list: merge generated exercises into base
  const exercises = useMemo(() => {
    return ALL_EXERCISES.map((ex) => {
      const gen = generatedExercises[ex.id];
      if (gen) {
        return {
          ...ex,
          prompt: gen.prompt,
          correctAnswer: gen.correctAnswer,
          generated: gen.generated,
        };
      }
      return ex;
    });
  }, [generatedExercises]);

  const activeExercise = useMemo(
    () => exercises.find((e) => e.id === activeExerciseId) ?? null,
    [activeExerciseId, exercises],
  );

  const exercisesByDifficulty = useMemo(() => {
    const grouped: Record<number, RawExercise[]> = { 1: [], 2: [], 3: [] };
    for (const ex of exercises) {
      grouped[ex.difficultyLevel]?.push(ex);
    }
    return grouped;
  }, [exercises]);

  // Progress data
  const progressData: FigureProgress[] = useMemo(() => {
    const figureMap = new Map<string, { completed: number; total: number; name: string }>();
    for (const ex of exercises) {
      const entry = figureMap.get(ex.figureSlug) ?? { completed: 0, total: 0, name: ex.figureName };
      entry.total++;
      if (submitted[ex.id]) entry.completed++;
      figureMap.set(ex.figureSlug, entry);
    }
    return Array.from(figureMap.entries()).map(([slug, data]) => ({
      figureSlug: slug,
      figureName: data.name,
      completed: data.completed,
      total: data.total,
    }));
  }, [exercises, submitted]);

  // Handlers
  const handleStartExercise = useCallback((id: number) => {
    setActiveExerciseId(id);
  }, []);

  const handleBack = useCallback(() => {
    setActiveExerciseId(null);
    setGenerateError(null);
  }, []);

  const handleAnswerChange = useCallback((value: string) => {
    if (activeExercise) {
      setAnswers((prev) => ({ ...prev, [activeExercise.id]: value }));
    }
  }, [activeExercise]);

  const handleSubmit = useCallback(() => {
    if (!activeExercise) return;
    const userAnswer = answers[activeExercise.id] ?? "";
    const result = checkAnswer(
      activeExercise.type,
      userAnswer,
      activeExercise.correctAnswer,
    );
    setResults((prev) => ({ ...prev, [activeExercise.id]: result.correct }));
    setSubmitted((prev) => ({ ...prev, [activeExercise.id]: true }));
  }, [activeExercise, answers]);

  const handleNext = useCallback(() => {
    if (!activeExercise) return;
    const currentIndex = exercises.findIndex((e) => e.id === activeExercise.id);
    const nextExercise = exercises[currentIndex + 1];
    if (nextExercise) {
      setActiveExerciseId(nextExercise.id);
    } else {
      setActiveExerciseId(null);
    }
  }, [activeExercise, exercises]);

  // AI generation handler
  const handleGenerate = useCallback(
    async (ex: RawExercise) => {
      setGeneratingIds((prev) => new Set(prev).add(ex.id));
      setGenerateError(null);

      try {
        const response = await fetch("/api/ai/generate-exercise", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            figureSlug: ex.figureSlug,
            type: ex.type,
            difficulty: ex.difficultyLevel,
            locale: "es",
          }),
        });

        if (!response.ok) {
          throw new Error("Generation failed");
        }

        const data = await response.json();

        setGeneratedExercises((prev) => ({
          ...prev,
          [ex.id]: {
            // For identification, wrap the AI-generated text in a question
            prompt:
              ex.type === "identification"
                ? `¿Qué figura retórica se usa en el siguiente texto?\n\n"${data.text}"`
                : data.text,
            // For identification, use the figure name (not slug) as answer
            correctAnswer:
              ex.type === "identification" ? ex.figureName : data.answer,
            generated: true,
          },
        }));
      } catch {
        setGenerateError(t("generateError"));
      } finally {
        setGeneratingIds((prev) => {
          const next = new Set(prev);
          next.delete(ex.id);
          return next;
        });
      }
    },
    [t],
  );

  // -----------------------------------------------------------------------
  // Individual exercise view
  // -----------------------------------------------------------------------

  if (activeExercise) {
    const ex = activeExercise;
    const userAnswer = answers[ex.id] ?? "";
    const isSubmitted = submitted[ex.id] ?? false;
    const isCorrect = results[ex.id] ?? false;

    return (
      <div className="min-h-screen bg-gray-50/60">
        <div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
          {/* Back button */}
          <button
            type="button"
            onClick={handleBack}
            className="mb-6 flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700 transition-colors"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
            </svg>
            {t("back")}
          </button>

          <ExerciseCard exercise={ex as ExerciseData} answered={isSubmitted}>
            {/* Answer area */}
            {ex.type === "identification" && ex.options ? (
              <IdentificationExercise
                options={ex.options}
                selectedOption={userAnswer}
                answered={isSubmitted}
                correctAnswer={ex.correctAnswer}
                onSelect={(option) => handleAnswerChange(option)}
              />
            ) : ex.type === "identification" ? (
              /* AI-generated identification exercises have no options — show text input */
              <div className="space-y-3">
                <p className="text-xs text-gray-500">
                  {t("type.identification")}
                </p>
                <input
                  type="text"
                  value={userAnswer}
                  onChange={(e) => handleAnswerChange(e.target.value)}
                  disabled={isSubmitted}
                  placeholder={t("placeholder")}
                  className={cn(
                    "w-full rounded-lg border px-4 py-3 text-sm transition-all",
                    "placeholder:text-gray-400",
                    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2",
                    !isSubmitted && "border-gray-300 bg-white",
                    isSubmitted && isCorrect && "border-emerald-400 bg-emerald-50 text-emerald-800",
                    isSubmitted && !isCorrect && "border-rose-300 bg-rose-50 text-rose-700",
                    isSubmitted && "cursor-default",
                  )}
                />
                {isSubmitted && !isCorrect && (
                  <p className="text-xs text-gray-500">
                    Una posibilidad:{" "}
                    <span className="font-medium text-gray-700">
                      {ex.correctAnswer}
                    </span>
                  </p>
                )}
              </div>
            ) : (
              <CompletionExercise
                value={userAnswer}
                answered={isSubmitted}
                correctAnswer={ex.correctAnswer}
                onChange={handleAnswerChange}
              />
            )}

            {/* Action buttons */}
            <div className="mt-4 flex items-center gap-3">
              {!isSubmitted ? (
                <Button
                  onClick={handleSubmit}
                  disabled={
                    ex.type === "completion"
                      ? userAnswer.trim().length === 0
                      : userAnswer.length === 0
                  }
                  size="sm"
                >
                  {t("submit")}
                </Button>
              ) : (
                <Button onClick={handleNext} variant="outline" size="sm">
                  {t("next")}
                </Button>
              )}
            </div>
          </ExerciseCard>

          {/* Feedback */}
          {isSubmitted && (
            <div className="mt-4">
              <ExerciseFeedback
                isCorrect={isCorrect}
                figureName={ex.figureName}
              />
            </div>
          )}
        </div>
      </div>
    );
  }

  // -----------------------------------------------------------------------
  // Exercise list (grouped by difficulty)
  // -----------------------------------------------------------------------

  return (
    <div className="min-h-screen bg-gray-50/60">
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">
            {t("title")}
          </h1>
          <p className="mt-1 text-sm text-gray-500">{t("description")}</p>
        </div>

        {/* Generate error toast */}
        {generateError && (
          <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">
            {generateError}
          </div>
        )}

        {/* Content grid: exercises + progress sidebar */}
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-4">
          {/* Exercises column */}
          <div className="lg:col-span-3 space-y-8">
            {DIFFICULTY_CONFIG.map((cfg) => {
              const levelExercises = exercisesByDifficulty[cfg.level];
              if (!levelExercises || levelExercises.length === 0) return null;
              const completed = levelExercises.filter((e) => submitted[e.id]).length;

              return (
                <section key={cfg.level}>
                  <div className="mb-3 flex items-center gap-3">
                    <h2 className="text-lg font-semibold text-gray-900">
                      {cfg.label}
                    </h2>
                    <span className="text-xs text-gray-400">
                      {completed}/{levelExercises.length}
                    </span>
                  </div>

                  <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                    {levelExercises.map((ex) => {
                      const isSubmitted = submitted[ex.id] ?? false;
                      const isCorrect = results[ex.id] ?? false;
                      const isGenerating = generatingIds.has(ex.id);
                      const isGenerated = ex.generated ?? false;

                      return (
                        <button
                          key={ex.id}
                          type="button"
                          onClick={() => handleStartExercise(ex.id)}
                          className={cn(
                            "flex flex-col items-start rounded-xl border bg-white p-4 text-left shadow-sm transition-all",
                            "hover:border-gray-300 hover:shadow-md",
                            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2",
                            isSubmitted && isCorrect && "border-emerald-200 bg-emerald-50/40",
                            isSubmitted && !isCorrect && "border-amber-200 bg-amber-50/40",
                            isGenerating && "opacity-60 pointer-events-none",
                          )}
                          disabled={isGenerating}
                        >
                          <div className="flex w-full items-center justify-between gap-2">
                            <span
                              className={cn(
                                "rounded-full px-2 py-0.5 text-xs font-medium",
                                ex.difficultyLevel === 1 && "bg-emerald-100 text-emerald-700",
                                ex.difficultyLevel === 2 && "bg-amber-100 text-amber-700",
                                ex.difficultyLevel === 3 && "bg-rose-100 text-rose-700",
                              )}
                            >
                              {ex.figureName}
                            </span>
                            <div className="flex items-center gap-1.5">
                              {/* "New" indicator for generated exercises */}
                              {isGenerated && (
                                <span className="rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] font-semibold text-emerald-600">
                                  {t("newIndicator")}
                                </span>
                              )}
                              <span
                                className={cn(
                                  "rounded px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide",
                                  ex.type === "identification"
                                    ? "bg-blue-50 text-blue-600"
                                    : "bg-purple-50 text-purple-600",
                                )}
                              >
                                {ex.type === "identification" ? "ID" : "COMP"}
                              </span>
                            </div>
                          </div>
                          <p className="mt-2 text-xs leading-relaxed text-gray-600 line-clamp-2">
                            {ex.prompt}
                          </p>
                          <div className="mt-2 flex w-full items-center justify-between">
                            <div>
                              {isSubmitted && (
                                <span
                                  className={cn(
                                    "text-xs font-medium",
                                    isCorrect ? "text-emerald-600" : "text-amber-600",
                                  )}
                                >
                                  {isCorrect ? "✓ Completado" : "○ Intentado"}
                                </span>
                              )}
                            </div>
                            {/* Generate button */}
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleGenerate(ex);
                              }}
                              disabled={isGenerating}
                              className={cn(
                                "flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-medium transition-colors",
                                "text-gray-400 hover:text-emerald-600 hover:bg-emerald-50",
                                "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500",
                                isGenerating && "pointer-events-none text-emerald-500",
                              )}
                            >
                              {isGenerating ? (
                                <>
                                  <Spinner className="h-3 w-3" />
                                  {t("generating")}
                                </>
                              ) : (
                                t("generate")
                              )}
                            </button>
                          </div>
                        </button>
                      );
                    })}
                  </div>
                </section>
              );
            })}
          </div>

          {/* Progress sidebar */}
          <div className="lg:col-span-1">
            <div className="sticky top-8">
              <h3 className="mb-3 text-sm font-semibold text-gray-900">
                {t("progress")}
              </h3>
              <ExerciseProgress progress={progressData} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
